//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym_Check.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Asistencias
    {
        public int id_bitacoras { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<bool> Instructor { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> id_responsable { get; set; }
    }
}
