//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym_Check.App_Code.Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_Finger_ModelContainer : DbContext
    {
        public db_Finger_ModelContainer()
            : base("name=db_Finger_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Usuarios> tb_Usuarios { get; set; }
    
        public virtual int sp_Guardar_Dedo(Nullable<bool> dedo)
        {
            var dedoParameter = dedo.HasValue ?
                new ObjectParameter("dedo", dedo) :
                new ObjectParameter("dedo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Guardar_Dedo", dedoParameter);
        }
    }
}
