//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym_Check.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public byte[] dedo { get; set; }
    }
}
