//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_Metodos_Pagos
    {
        public int id_metodo_pago { get; set; }
        public string nombre_metodo_pago { get; set; }
    }
}
