//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costo_Cliente_Periodo
    {
        public int id_costo_cliente_periodo { get; set; }
        public Nullable<int> id_periodo { get; set; }
        public Nullable<int> id_tipo_cliente { get; set; }
        public Nullable<decimal> costo { get; set; }
    }
}
