//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym.App_Code.Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class db_sporting_gymContainer : DbContext
    {
        public db_sporting_gymContainer()
            : base("name=db_sporting_gymContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Catalogo_Tipos_Egresos> Catalogo_Tipos_Egresos { get; set; }
        public DbSet<Catalogo_Metodos_Pagos> Catalogo_Metodos_Pagos { get; set; }
        public DbSet<Catalogo_Periodos> Catalogo_Periodos { get; set; }
        public DbSet<Catalogo_Tipos_Clientes> Catalogo_Tipos_Clientes { get; set; }
        public DbSet<Costo_Cliente_Periodo> Costo_Cliente_Periodo { get; set; }
        public DbSet<Generales_Accesos> Generales_Accesos { get; set; }
        public DbSet<Generales_Accesos_Usuarios> Generales_Accesos_Usuarios { get; set; }
        public DbSet<Bitacora_Asistencias> Bitacora_Asistencias { get; set; }
        public DbSet<Tabla_Pagos> Tabla_Pagos { get; set; }
        public DbSet<Catalogo_Colonias> Catalogo_Colonias { get; set; }
        public DbSet<Catalogo_Clientes> Catalogo_Clientes { get; set; }
        public DbSet<Catalogo_Instructores> Catalogo_Instructores { get; set; }
        public DbSet<Archivos_Clientes> Archivos_Clientes { get; set; }
        public DbSet<Generales_Usuarios> Generales_Usuarios { get; set; }
        public DbSet<Tabla_Egresos> Tabla_Egresos { get; set; }
        public DbSet<Grupos> Grupos { get; set; }
    
        public virtual int sp_Eliminar_Cliente_Catalogo(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Cliente_Catalogo", id_clienteParameter);
        }
    
        public virtual int sp_Eliminar_Grupo_Catalogo(Nullable<int> id_grupo)
        {
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Grupo_Catalogo", id_grupoParameter);
        }
    
        public virtual int sp_Eliminar_Instructor_Catalogo(Nullable<int> id_instructor)
        {
            var id_instructorParameter = id_instructor.HasValue ?
                new ObjectParameter("id_instructor", id_instructor) :
                new ObjectParameter("id_instructor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Instructor_Catalogo", id_instructorParameter);
        }
    
        public virtual int sp_Eliminar_Periodo_Catalogo(Nullable<int> id_periodo)
        {
            var id_periodoParameter = id_periodo.HasValue ?
                new ObjectParameter("id_periodo", id_periodo) :
                new ObjectParameter("id_periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Periodo_Catalogo", id_periodoParameter);
        }
    
        public virtual int sp_Eliminar_Tipo_Clientes_Catalogo(Nullable<int> id_tipo_cliente)
        {
            var id_tipo_clienteParameter = id_tipo_cliente.HasValue ?
                new ObjectParameter("id_tipo_cliente", id_tipo_cliente) :
                new ObjectParameter("id_tipo_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Tipo_Clientes_Catalogo", id_tipo_clienteParameter);
        }
    
        public virtual int sp_Eliminar_Tipo_Egresos_Catalogo(Nullable<int> id_tipo_egresos)
        {
            var id_tipo_egresosParameter = id_tipo_egresos.HasValue ?
                new ObjectParameter("id_tipo_egresos", id_tipo_egresos) :
                new ObjectParameter("id_tipo_egresos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Tipo_Egresos_Catalogo", id_tipo_egresosParameter);
        }
    
        public virtual int sp_Eliminar_Tipo_Pagos_Catalogo(Nullable<int> id_tipo_pago)
        {
            var id_tipo_pagoParameter = id_tipo_pago.HasValue ?
                new ObjectParameter("id_tipo_pago", id_tipo_pago) :
                new ObjectParameter("id_tipo_pago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_Tipo_Pagos_Catalogo", id_tipo_pagoParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Tipo_Clientes_Result> sp_Buscar_Tipo_Clientes(string nombre_tipo_cliente)
        {
            var nombre_tipo_clienteParameter = nombre_tipo_cliente != null ?
                new ObjectParameter("nombre_tipo_cliente", nombre_tipo_cliente) :
                new ObjectParameter("nombre_tipo_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Tipo_Clientes_Result>("sp_Buscar_Tipo_Clientes", nombre_tipo_clienteParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Tipo_Egresos_Result> sp_Buscar_Tipo_Egresos(string nombre_tipo_egreso)
        {
            var nombre_tipo_egresoParameter = nombre_tipo_egreso != null ?
                new ObjectParameter("nombre_tipo_egreso", nombre_tipo_egreso) :
                new ObjectParameter("nombre_tipo_egreso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Tipo_Egresos_Result>("sp_Buscar_Tipo_Egresos", nombre_tipo_egresoParameter);
        }
    
        public virtual int sp_Insertar_Grupo_Catalogo(string nombre_grupo)
        {
            var nombre_grupoParameter = nombre_grupo != null ?
                new ObjectParameter("nombre_grupo", nombre_grupo) :
                new ObjectParameter("nombre_grupo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insertar_Grupo_Catalogo", nombre_grupoParameter);
        }
    
        public virtual ObjectResult<sp_Leer_Tipo_Clientes_Result> sp_Leer_Tipo_Clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Leer_Tipo_Clientes_Result>("sp_Leer_Tipo_Clientes");
        }
    
        public virtual ObjectResult<sp_Leer_Tipo_Egresos_Result> sp_Leer_Tipo_Egresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Leer_Tipo_Egresos_Result>("sp_Leer_Tipo_Egresos");
        }
    
        public virtual ObjectResult<sp_Leer_Tipo_Pagos_Result> sp_Leer_Tipo_Pagos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Leer_Tipo_Pagos_Result>("sp_Leer_Tipo_Pagos");
        }
    
        public virtual int sp_Actualizar_Periodo(Nullable<int> id_periodo, string nombre_periodo, Nullable<int> dias_periodo)
        {
            var id_periodoParameter = id_periodo.HasValue ?
                new ObjectParameter("id_periodo", id_periodo) :
                new ObjectParameter("id_periodo", typeof(int));
    
            var nombre_periodoParameter = nombre_periodo != null ?
                new ObjectParameter("nombre_periodo", nombre_periodo) :
                new ObjectParameter("nombre_periodo", typeof(string));
    
            var dias_periodoParameter = dias_periodo.HasValue ?
                new ObjectParameter("dias_periodo", dias_periodo) :
                new ObjectParameter("dias_periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Periodo", id_periodoParameter, nombre_periodoParameter, dias_periodoParameter);
        }
    
        public virtual int sp_Nuevo_Periodo(string nombre_periodo, Nullable<int> dias_periodo)
        {
            var nombre_periodoParameter = nombre_periodo != null ?
                new ObjectParameter("nombre_periodo", nombre_periodo) :
                new ObjectParameter("nombre_periodo", typeof(string));
    
            var dias_periodoParameter = dias_periodo.HasValue ?
                new ObjectParameter("dias_periodo", dias_periodo) :
                new ObjectParameter("dias_periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Nuevo_Periodo", nombre_periodoParameter, dias_periodoParameter);
        }
    
        public virtual int sp_Actualizar_Metodos_Pago(Nullable<int> id_Metodos_Pago, string nombre__Metodos_Pago)
        {
            var id_Metodos_PagoParameter = id_Metodos_Pago.HasValue ?
                new ObjectParameter("id_Metodos_Pago", id_Metodos_Pago) :
                new ObjectParameter("id_Metodos_Pago", typeof(int));
    
            var nombre__Metodos_PagoParameter = nombre__Metodos_Pago != null ?
                new ObjectParameter("nombre__Metodos_Pago", nombre__Metodos_Pago) :
                new ObjectParameter("nombre__Metodos_Pago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Metodos_Pago", id_Metodos_PagoParameter, nombre__Metodos_PagoParameter);
        }
    
        public virtual int sp_Actualizar_Tipo_Cliente(Nullable<int> id_tipo_cliente, string nombre_tipo_cliente)
        {
            var id_tipo_clienteParameter = id_tipo_cliente.HasValue ?
                new ObjectParameter("id_tipo_cliente", id_tipo_cliente) :
                new ObjectParameter("id_tipo_cliente", typeof(int));
    
            var nombre_tipo_clienteParameter = nombre_tipo_cliente != null ?
                new ObjectParameter("nombre_tipo_cliente", nombre_tipo_cliente) :
                new ObjectParameter("nombre_tipo_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Tipo_Cliente", id_tipo_clienteParameter, nombre_tipo_clienteParameter);
        }
    
        public virtual int sp_Actualizar_Tipo_Egreso(Nullable<int> id_tipo_egreso, string nombre_tipo_egreso)
        {
            var id_tipo_egresoParameter = id_tipo_egreso.HasValue ?
                new ObjectParameter("id_tipo_egreso", id_tipo_egreso) :
                new ObjectParameter("id_tipo_egreso", typeof(int));
    
            var nombre_tipo_egresoParameter = nombre_tipo_egreso != null ?
                new ObjectParameter("nombre_tipo_egreso", nombre_tipo_egreso) :
                new ObjectParameter("nombre_tipo_egreso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Tipo_Egreso", id_tipo_egresoParameter, nombre_tipo_egresoParameter);
        }
    
        public virtual int sp_Nuevo_Metodo_Pago(string nombre_Metodo_Pago)
        {
            var nombre_Metodo_PagoParameter = nombre_Metodo_Pago != null ?
                new ObjectParameter("nombre_Metodo_Pago", nombre_Metodo_Pago) :
                new ObjectParameter("nombre_Metodo_Pago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Nuevo_Metodo_Pago", nombre_Metodo_PagoParameter);
        }
    
        public virtual int sp_Nuevo_Tipo_Cliente(string nombre_tipo_cliente)
        {
            var nombre_tipo_clienteParameter = nombre_tipo_cliente != null ?
                new ObjectParameter("nombre_tipo_cliente", nombre_tipo_cliente) :
                new ObjectParameter("nombre_tipo_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Nuevo_Tipo_Cliente", nombre_tipo_clienteParameter);
        }
    
        public virtual int sp_Nuevo_Tipo_Egreso(string nombre_tipo_egreso)
        {
            var nombre_tipo_egresoParameter = nombre_tipo_egreso != null ?
                new ObjectParameter("nombre_tipo_egreso", nombre_tipo_egreso) :
                new ObjectParameter("nombre_tipo_egreso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Nuevo_Tipo_Egreso", nombre_tipo_egresoParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Tipo_Pagos_Result> sp_Buscar_Tipo_Pagos(string nombre_tipo_pago)
        {
            var nombre_tipo_pagoParameter = nombre_tipo_pago != null ?
                new ObjectParameter("nombre_tipo_pago", nombre_tipo_pago) :
                new ObjectParameter("nombre_tipo_pago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Tipo_Pagos_Result>("sp_Buscar_Tipo_Pagos", nombre_tipo_pagoParameter);
        }
    
        public virtual ObjectResult<sp_Leer_Clientes_Result> sp_Leer_Clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Leer_Clientes_Result>("sp_Leer_Clientes");
        }
    
        public virtual ObjectResult<sp_Buscar_Periodo_Result> sp_Buscar_Periodo(string nombre_periodo)
        {
            var nombre_periodoParameter = nombre_periodo != null ?
                new ObjectParameter("nombre_periodo", nombre_periodo) :
                new ObjectParameter("nombre_periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Periodo_Result>("sp_Buscar_Periodo", nombre_periodoParameter);
        }
    
        public virtual int sp_Agrega_Nuevo_Instructor(string ape_paterno, string ape_materno, string nombre, Nullable<System.DateTime> fecha_nacimiento, string sexo, Nullable<int> edad, string calle, string numero, string colonia, string correo, string telefono, string celular, Nullable<System.DateTime> fecha_ingreso, Nullable<bool> estatus, byte[] foto)
        {
            var ape_paternoParameter = ape_paterno != null ?
                new ObjectParameter("ape_paterno", ape_paterno) :
                new ObjectParameter("ape_paterno", typeof(string));
    
            var ape_maternoParameter = ape_materno != null ?
                new ObjectParameter("ape_materno", ape_materno) :
                new ObjectParameter("ape_materno", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var coloniaParameter = colonia != null ?
                new ObjectParameter("colonia", colonia) :
                new ObjectParameter("colonia", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            var fecha_ingresoParameter = fecha_ingreso.HasValue ?
                new ObjectParameter("fecha_ingreso", fecha_ingreso) :
                new ObjectParameter("fecha_ingreso", typeof(System.DateTime));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(bool));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Agrega_Nuevo_Instructor", ape_paternoParameter, ape_maternoParameter, nombreParameter, fecha_nacimientoParameter, sexoParameter, edadParameter, calleParameter, numeroParameter, coloniaParameter, correoParameter, telefonoParameter, celularParameter, fecha_ingresoParameter, estatusParameter, fotoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Importe_Pagar(Nullable<int> id_tipo_cliente, Nullable<int> id_periodo)
        {
            var id_tipo_clienteParameter = id_tipo_cliente.HasValue ?
                new ObjectParameter("id_tipo_cliente", id_tipo_cliente) :
                new ObjectParameter("id_tipo_cliente", typeof(int));
    
            var id_periodoParameter = id_periodo.HasValue ?
                new ObjectParameter("id_periodo", id_periodo) :
                new ObjectParameter("id_periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Importe_Pagar", id_tipo_clienteParameter, id_periodoParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Pago_Result> sp_Buscar_Pago(Nullable<int> id_pago)
        {
            var id_pagoParameter = id_pago.HasValue ?
                new ObjectParameter("id_pago", id_pago) :
                new ObjectParameter("id_pago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Pago_Result>("sp_Buscar_Pago", id_pagoParameter);
        }
    
        public virtual int sp_Actualizar_Huella(Nullable<int> id_cliente, byte[] huella, Nullable<bool> persona)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var huellaParameter = huella != null ?
                new ObjectParameter("huella", huella) :
                new ObjectParameter("huella", typeof(byte[]));
    
            var personaParameter = persona.HasValue ?
                new ObjectParameter("persona", persona) :
                new ObjectParameter("persona", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Huella", id_clienteParameter, huellaParameter, personaParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Grupo_Result> sp_Buscar_Grupo(string nombre_grupo)
        {
            var nombre_grupoParameter = nombre_grupo != null ?
                new ObjectParameter("nombre_grupo", nombre_grupo) :
                new ObjectParameter("nombre_grupo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Grupo_Result>("sp_Buscar_Grupo", nombre_grupoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Nuevo_Grupo(string nombre_grupo)
        {
            var nombre_grupoParameter = nombre_grupo != null ?
                new ObjectParameter("nombre_grupo", nombre_grupo) :
                new ObjectParameter("nombre_grupo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Nuevo_Grupo", nombre_grupoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Actualizar_Cliente_Pago(Nullable<int> id_cliente, Nullable<int> id_tipo_cliente, Nullable<int> id_periodo, Nullable<int> id_metodo_pago, Nullable<int> id_grupo, Nullable<double> importe_a_pagar, Nullable<double> recibido, Nullable<double> cambio, Nullable<double> importe_pagado, string justificacion, string observaciones, Nullable<System.DateTime> fecha_corte, Nullable<int> id_usuario_capturo)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_tipo_clienteParameter = id_tipo_cliente.HasValue ?
                new ObjectParameter("id_tipo_cliente", id_tipo_cliente) :
                new ObjectParameter("id_tipo_cliente", typeof(int));
    
            var id_periodoParameter = id_periodo.HasValue ?
                new ObjectParameter("id_periodo", id_periodo) :
                new ObjectParameter("id_periodo", typeof(int));
    
            var id_metodo_pagoParameter = id_metodo_pago.HasValue ?
                new ObjectParameter("id_metodo_pago", id_metodo_pago) :
                new ObjectParameter("id_metodo_pago", typeof(int));
    
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            var importe_a_pagarParameter = importe_a_pagar.HasValue ?
                new ObjectParameter("importe_a_pagar", importe_a_pagar) :
                new ObjectParameter("importe_a_pagar", typeof(double));
    
            var recibidoParameter = recibido.HasValue ?
                new ObjectParameter("recibido", recibido) :
                new ObjectParameter("recibido", typeof(double));
    
            var cambioParameter = cambio.HasValue ?
                new ObjectParameter("cambio", cambio) :
                new ObjectParameter("cambio", typeof(double));
    
            var importe_pagadoParameter = importe_pagado.HasValue ?
                new ObjectParameter("importe_pagado", importe_pagado) :
                new ObjectParameter("importe_pagado", typeof(double));
    
            var justificacionParameter = justificacion != null ?
                new ObjectParameter("justificacion", justificacion) :
                new ObjectParameter("justificacion", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var fecha_corteParameter = fecha_corte.HasValue ?
                new ObjectParameter("fecha_corte", fecha_corte) :
                new ObjectParameter("fecha_corte", typeof(System.DateTime));
    
            var id_usuario_capturoParameter = id_usuario_capturo.HasValue ?
                new ObjectParameter("id_usuario_capturo", id_usuario_capturo) :
                new ObjectParameter("id_usuario_capturo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Actualizar_Cliente_Pago", id_clienteParameter, id_tipo_clienteParameter, id_periodoParameter, id_metodo_pagoParameter, id_grupoParameter, importe_a_pagarParameter, recibidoParameter, cambioParameter, importe_pagadoParameter, justificacionParameter, observacionesParameter, fecha_corteParameter, id_usuario_capturoParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Colonia_Result> sp_Buscar_Colonia(string nombre_colonia)
        {
            var nombre_coloniaParameter = nombre_colonia != null ?
                new ObjectParameter("nombre_colonia", nombre_colonia) :
                new ObjectParameter("nombre_colonia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Colonia_Result>("sp_Buscar_Colonia", nombre_coloniaParameter);
        }
    
        public virtual int sp_Actualizar_Cliente(Nullable<int> id_cliente, string nombre, string ape_paterno, string ape_materno, Nullable<System.DateTime> fecha_nacimiento, string sexo, Nullable<int> edad, string calle, string numero, string colonia, string correo, string celular, byte[] foto, Nullable<bool> estatus)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ape_paternoParameter = ape_paterno != null ?
                new ObjectParameter("ape_paterno", ape_paterno) :
                new ObjectParameter("ape_paterno", typeof(string));
    
            var ape_maternoParameter = ape_materno != null ?
                new ObjectParameter("ape_materno", ape_materno) :
                new ObjectParameter("ape_materno", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var coloniaParameter = colonia != null ?
                new ObjectParameter("colonia", colonia) :
                new ObjectParameter("colonia", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Cliente", id_clienteParameter, nombreParameter, ape_paternoParameter, ape_maternoParameter, fecha_nacimientoParameter, sexoParameter, edadParameter, calleParameter, numeroParameter, coloniaParameter, correoParameter, celularParameter, fotoParameter, estatusParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Clientes_Id_Result> sp_Buscar_Clientes_Id(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Clientes_Id_Result>("sp_Buscar_Clientes_Id", id_clienteParameter);
        }
    
        public virtual int sp_Actualizar_Instructor(Nullable<int> id_instructor, string ape_paterno, string ape_materno, string nombre, Nullable<System.DateTime> fecha_nacimiento, string sexo, Nullable<int> edad, string calle, string numero, string colonia, string correo, string celular, byte[] foto, Nullable<bool> estatus)
        {
            var id_instructorParameter = id_instructor.HasValue ?
                new ObjectParameter("id_instructor", id_instructor) :
                new ObjectParameter("id_instructor", typeof(int));
    
            var ape_paternoParameter = ape_paterno != null ?
                new ObjectParameter("ape_paterno", ape_paterno) :
                new ObjectParameter("ape_paterno", typeof(string));
    
            var ape_maternoParameter = ape_materno != null ?
                new ObjectParameter("ape_materno", ape_materno) :
                new ObjectParameter("ape_materno", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var coloniaParameter = colonia != null ?
                new ObjectParameter("colonia", colonia) :
                new ObjectParameter("colonia", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_Instructor", id_instructorParameter, ape_paternoParameter, ape_maternoParameter, nombreParameter, fecha_nacimientoParameter, sexoParameter, edadParameter, calleParameter, numeroParameter, coloniaParameter, correoParameter, celularParameter, fotoParameter, estatusParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Cliente_Result1> sp_Buscar_Cliente(string nombre_buscar)
        {
            var nombre_buscarParameter = nombre_buscar != null ?
                new ObjectParameter("nombre_buscar", nombre_buscar) :
                new ObjectParameter("nombre_buscar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Cliente_Result1>("sp_Buscar_Cliente", nombre_buscarParameter);
        }
    
        public virtual ObjectResult<sp_Buscar_Instructor_Result> sp_Buscar_Instructor(string nombre_intructor)
        {
            var nombre_intructorParameter = nombre_intructor != null ?
                new ObjectParameter("nombre_intructor", nombre_intructor) :
                new ObjectParameter("nombre_intructor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Instructor_Result>("sp_Buscar_Instructor", nombre_intructorParameter);
        }
    
        public virtual ObjectResult<sp_Leer_Fechas_Pagos_Result> sp_Leer_Fechas_Pagos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Leer_Fechas_Pagos_Result>("sp_Leer_Fechas_Pagos");
        }
    
        public virtual ObjectResult<sp_Leer_Egresos_Result> sp_Leer_Egresos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Leer_Egresos_Result>("sp_Leer_Egresos");
        }
    
        public virtual ObjectResult<sp_Buscar_Historial_Pagos_Result> sp_Buscar_Historial_Pagos(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Buscar_Historial_Pagos_Result>("sp_Buscar_Historial_Pagos", id_clienteParameter);
        }
    
        public virtual int sp_Leer_Asistencias(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Leer_Asistencias", id_clienteParameter);
        }
    }
}
