//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generales_Accesos
    {
        public int id_acceso { get; set; }
        public string orden { get; set; }
        public string nombre_acceso { get; set; }
        public string titulo_boton { get; set; }
        public string nombre_form { get; set; }
        public Nullable<int> padre { get; set; }
        public string form_button { get; set; }
        public string store_procedure { get; set; }
    }
}
