//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla_Pagos
    {
        public int id_pago { get; set; }
        public Nullable<int> id_metodo_pago { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<System.DateTime> fecha_corte { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_periodo { get; set; }
        public Nullable<int> id_tipo_cliente { get; set; }
        public Nullable<double> importe_a_pagar { get; set; }
        public Nullable<double> importe_pagado { get; set; }
        public Nullable<double> recibido { get; set; }
        public Nullable<double> cambio { get; set; }
        public string justificacion { get; set; }
        public string observaciones { get; set; }
        public int id_usuario_capturo { get; set; }
        public Nullable<bool> cancelado { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
        public Nullable<int> id_usuario_cancelo { get; set; }
        public string justificacion_cancelacion { get; set; }
    }
}
