//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting_Gym.App_Code.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla_Egresos
    {
        public int id_egreso { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_tipo_egreso { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string justificacion { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
